### ISSUE TITLE
Writing  or reading empty series may be broken

### ISSUE THREAD

**Issue by jasonjensen** [bankofcanada/FAME.jl#8]
There is a potential issue with reading and writing empty TSeries to a fame db; the read series does not have the same start date.

![image](https://user-images.githubusercontent.com/7598563/201792331-af5b6326-7a1a-4fe5-927c-f713c5fd9b29.png)

steps to reproduce:
```
k = Workspace(;t1 = TSeries(1995Q1))
writefame("test.db", k)
readfame("test.db")
```

Reading the db in FAME does not provide much clarity:
![image](https://user-images.githubusercontent.com/7598563/201792889-335ef861-6405-4c3c-95be-48f39fafacb8.png)

**Comment by bbejanov** [comment]
Thanks for reporting that, Jason. The problem is that empty series in FAME don't have starting dates, while in TimeSeriesEcon they do. So, the information about the first date gets lost when we write an empty series, and when we load it we assign the maximum Int value reinterpreted as an MIT for the first date.
